import { invoke } from "@tauri-apps/api/core";
import type { Task, Subtask, CreateTaskPayload, UpdateTaskPayload, Note, CreateNotePayload, UpdateNotePayload, AppSettings } from "../types";

export const api = {
  getTasks: () => invoke<Task[]>("get_tasks"),
  createTask: (task: CreateTaskPayload) => invoke<Task>("create_task", { task }),
  updateTask: (id: string, patch: UpdateTaskPayload) => invoke<Task>("update_task", { id, patch }),
  deleteTask: (id: string) => invoke<void>("delete_task", { id }),
  completeTask: (id: string) => invoke<Task>("complete_task", { id }),
  searchTasks: (query: string) => invoke<Task[]>("search_tasks", { query }),
  recordInput: () => invoke<void>("record_input"),
  openQuickCapture: (mode: "task" | "note") => invoke<void>("open_quick_capture", { mode }),
  getQuickMode: () => invoke<"task" | "note">("get_quick_mode"),
  aiRewrite: (taskId: string, title: string) => invoke<void>("ai_rewrite", { taskId, title }),
  aiSubtasks: (taskId: string, title: string) => invoke<void>("ai_subtasks", { taskId, title }),
  aiClassify: (taskId: string, title: string) => invoke<void>("ai_classify", { taskId, title }),
  getNotes: () => invoke<Note[]>("get_notes"),
  createNote: (note: CreateNotePayload) => invoke<Note>("create_note", { note }),
  updateNote: (id: string, patch: UpdateNotePayload) => invoke<Note>("update_note", { id, patch }),
  deleteNote: (id: string) => invoke<void>("delete_note", { id }),
  getActivityByDay: () => invoke<{ date: string; minutes: number }[]>("get_activity_by_day"),
  getTaskCompletionsByDay: () => invoke<{ date: string; completed: number }[]>("get_task_completions_by_day"),
  getCategoryDistribution: () => invoke<{ category: string; count: number }[]>("get_category_distribution"),
  getActiveIdleRatio: () =>
    invoke<{ today_active: number; today_idle: number; week_active: number; week_idle: number }>("get_active_idle_ratio"),
  dashboardInsight: () => invoke<void>("dashboard_insight"),
  summarizeDay: () => invoke<void>("summarize_day"),
  summarizeWeek: () => invoke<void>("summarize_week"),
  getSettings: () => invoke<AppSettings>("get_settings"),
  saveSettings: (settings: AppSettings) => invoke<void>("save_settings", { settings }),
  isWayland: () => invoke<boolean>("is_wayland"),
  exportData: (path: string) => invoke<void>("export", { path }),
  importData: (path: string) => invoke<void>("import", { path }),
  getSubtasks: (taskId: string) => invoke<Subtask[]>("get_subtasks", { taskId }),
  addSubtask: (taskId: string, title: string) => invoke<Subtask>("add_subtask", { taskId, title }),
  toggleSubtask: (id: string) => invoke<void>("toggle_subtask", { id }),
  deleteSubtask: (id: string) => invoke<void>("delete_subtask", { id }),
  defaultModelUrl: () => invoke<string>("default_model_url"),
  modelStatus: () => invoke<{ exists: boolean; size_bytes: number }>("model_status"),
  downloadModel: (url: string) => invoke<void>("download_model", { url }),
};
