import { invoke } from "@tauri-apps/api/core";
import type { Task, Subtask, CreateTaskPayload, UpdateTaskPayload, Note, CreateNotePayload, UpdateNotePayload, AppSettings, Project, UpdateProjectPayload } from "../types";

export const api = {
  getTasks: () => invoke<Task[]>("get_tasks"),
  createTask: (task: CreateTaskPayload) => invoke<Task>("create_task", { task }),
  updateTask: (id: string, patch: UpdateTaskPayload) => invoke<Task>("update_task", { id, patch }),
  deleteTask: (id: string) => invoke<void>("delete_task", { id }),
  completeTask: (id: string) => invoke<Task>("complete_task", { id }),
  searchTasks: (query: string) => invoke<Task[]>("search_tasks", { query }),
  getProjects: () => invoke<Project[]>("get_projects"),
  createProject: (project: { name: string; color?: string; target_date?: string | null }) =>
    invoke<Project>("create_project", { project }),
  updateProject: (id: string, patch: UpdateProjectPayload) =>
    invoke<void>("update_project", { id, patch }),
  deleteProject: (id: string) => invoke<void>("delete_project", { id }),
  recordInput: () => invoke<void>("record_input"),
  openQuickCapture: (mode: "task" | "note") => invoke<void>("open_quick_capture", { mode }),
  getQuickMode: () => invoke<"task" | "note">("get_quick_mode"),
  aiRewrite: (taskId: string, title: string) => invoke<void>("ai_rewrite", { taskId, title }),
  aiSubtasks: (taskId: string, title: string) => invoke<void>("ai_subtasks", { taskId, title }),
  aiClassify: (taskId: string, title: string) => invoke<void>("ai_classify", { taskId, title }),
  aiPlanDay: () => invoke<void>("ai_plan_day"),
  aiWhatNow: () => invoke<void>("ai_what_now"),
  getNotes: () => invoke<Note[]>("get_notes"),
  createNote: (note: CreateNotePayload) => invoke<Note>("create_note", { note }),
  updateNote: (id: string, patch: UpdateNotePayload) => invoke<Note>("update_note", { id, patch }),
  deleteNote: (id: string) => invoke<void>("delete_note", { id }),
  getActivityByDay: () => invoke<{ date: string; minutes: number }[]>("get_activity_by_day"),
  getTaskCompletionsByDay: () => invoke<{ date: string; completed: number }[]>("get_task_completions_by_day"),
  getCategoryDistribution: () => invoke<{ category: string; count: number }[]>("get_category_distribution"),
  getActiveIdleRatio: () =>
    invoke<{ today_active: number; today_idle: number; week_active: number; week_idle: number }>("get_active_idle_ratio"),
  getAppUsage: (days: number) => invoke<{ app: string; minutes: number }[]>("get_app_usage", { days }),
  getAppCategoryTime: (days: number) =>
    invoke<{ category: string; minutes: number }[]>("get_app_category_time", { days }),
  dashboardInsight: () => invoke<void>("dashboard_insight"),
  summarizeDay: () => invoke<void>("summarize_day"),
  summarizeWeek: () => invoke<void>("summarize_week"),
  getSettings: () => invoke<AppSettings>("get_settings"),
  saveSettings: (settings: AppSettings) => invoke<void>("save_settings", { settings }),
  isWayland: () => invoke<boolean>("is_wayland"),
  getTrackingMode: () => invoke<"extended" | "basic">("get_tracking_mode"),
  getWindowTracking: () => invoke<string | null>("get_window_tracking"),
  exportData: (path: string) => invoke<void>("export", { path }),
  importData: (path: string) => invoke<void>("import", { path }),
  getSubtasks: (taskId: string) => invoke<Subtask[]>("get_subtasks", { taskId }),
  addSubtask: (taskId: string, title: string) => invoke<Subtask>("add_subtask", { taskId, title }),
  toggleSubtask: (id: string) => invoke<void>("toggle_subtask", { id }),
  deleteSubtask: (id: string) => invoke<void>("delete_subtask", { id }),
  defaultModelUrl: () => invoke<string>("default_model_url"),
  modelStatus: () => invoke<{ exists: boolean; size_bytes: number }>("model_status"),
  downloadModel: (url: string) => invoke<void>("download_model", { url }),
};
