#!/bin/sh
DIR="$(dirname "$0")"
cd /tmp
if [ -f "$DIR/llamafile" ]; then
  exec "$DIR/llamafile" "$@"
elif [ -f "$DIR/llamafile-x86_64-unknown-linux-gnu" ]; then
  exec "$DIR/llamafile-x86_64-unknown-linux-gnu" "$@"
else
  echo "llamafile binary not found" >&2
  exit 1
fi
